### PR TITLE
Problem: latest cosmos-sdk commits require upgrading go1.17 to go1.18

### LINKED ISSUE #572: Problem: latest cosmos-sdk updates requires go1.18
**Is your feature request related to a problem? Please describe.**
I need to update cosmos-sdk to latest commit in `release/v0.45.x` to fix simulation failures.
but some updates requires go1.18 to build the binary.

**Describe the solution you'd like**
upgrade golang version in `go.mod`,  `Makefile`, `.github/workflows/build.yml` and `.github/workflows/lint.yml` to `go1.18`

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by adu-crypto**
👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

closes #572 

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest master? 
- [ ] Have you checked your code compiles? (`make`)
- [ ] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`make test`)
- [ ] Have you checked your code formatting is correct? (`go fmt`)
- [ ] Have you checked your basic code style is fine? (`golangci-lint run`)
- [ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`go list -json -m all | nancy sleuth`)
- [ ] If your changes affect the client infrastructure, have you run the integration test?
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-org-chain/chain-main/blob/master/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md#developer-certificate-of-originn).

Thank you for your code, it's appreciated! :)

### CODE REVIEW

**Review by tomtau — COMMENTED** [review]
I remember @yihuang mentioned there was some issue with Go 1.18 for Nix and macOS?

**Comment by adu-crypto** [comment]
> I remember @yihuang mentioned there was some issue with Go 1.18 for Nix and macOS?

oh, that is then troublesome.
some latest [commit](https://github.com/cosmos/cosmos-sdk/commit/f2d94445c0f5f52cf5ed999b81048b575de94964) in `release/v0.45.x` uses golang 1.18 generics.
```go
func GenericFilteredPaginate[T codec.ProtoMarshaler, F codec.ProtoMarshaler](
	cdc codec.BinaryCodec,
	prefixStore types.KVStore,
	pageRequest *PageRequest,
	onResult func(key []byte, value T) (F, error),
	constructor func() T,
) ([]F, *PageResponse, error) {
```

**Comment by yihuang** [comment]
I'm trying some nixpkgs patches to see if it works.

**Comment by yihuang** [comment]
> I'm trying some nixpkgs patches to see if it works.

still don't work: https://github.com/NixOS/nixpkgs/pull/176661#issuecomment-1175703967

**Comment by adu-crypto** [comment]
> [yihuang@edb7406](https://github.com/yihuang/cronos/commit/edb740603a4b8783d49e9ddf3da86b5c31a85c83)
> 
> @adu-crypto you can cherry-pick this commit, it should work in nix now.

great!

**Comment by yihuang** [comment]
Can you sign the commits?

**Comment by adu-crypto** [comment]
> Can you sign the commits?

yeah, I need to reset my yubikey first

**Comment by adu-crypto** [comment]
@yihuang signed

**Pull request merged**
