### PR TITLE
Run simulation tests in CI

### LINKED ISSUE #20: Problem: simulation tests is not run
Should add simulation test and run in CI.

### PR DESCRIPTION
**Pull request by yihuang**
Closes #20

- add simulation test and run in ci
  - will run when merged to main branch, or triggered manually
- fix export issue

👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest master? 
- [ ] Have you checked your code compiles? (`make`)
- [ ] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`make test`)
- [ ] Have you checked your code formatting is correct? (`go fmt`)
- [ ] Have you checked your basic code style is fine? (`golangci-lint run`)
- [ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`go list -json -m all | nancy sleuth`)
- [ ] If your changes affect the client infrastructure, have you run the integration test?
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-org-chain/chain-main/blob/master/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md#developer-certificate-of-originn).

Thank you for your code, it's appreciated! :)

### CODE REVIEW

**Review by tomtau — COMMENTED** [review]
the simulation tests usually take a long time, so maybe better not to run it on every pull request change -- just run it on demand or on the main branch?

**Comment by yihuang** [comment]
> the simulation tests usually take a long time, so maybe better not to run it on every pull request change -- just run it on demand or on the main branch?

I think the `workflow_dispatch` event could work [manually run workflow](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/), but the workflow need to be in default branch before we can run it manually.

**Comment by yihuang** [comment]
> > the simulation tests usually take a long time, so maybe better not to run it on every pull request change -- just run it on demand or on the main branch?
> 
> I think the `workflow_dispatch` event could work [manually run workflow](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/), but the workflow need to be in default branch before we can run it manually.

I tried locally, `test-sim-after-import` is still running, the other three all success. I think after merged this, in the next PR we can run the workflow manually.

**Comment by yihuang** [comment]
local run succeeded.

**Review by tomtau — COMMENTED** [review]
looks ok -- maybe in the future, it'll be good to add some generators for the EVM module?

**Comment by yihuang** [comment]
> looks ok -- maybe in the future, it'll be good to add some generators for the EVM module?

yeah, that could be done in the ethermint side.

**Review by tomtau — APPROVED** [review]

**Pull request merged**
