### PR TITLE
Feature Request: Enhance blacklist logging visibility (Issue #1333)

### PR DESCRIPTION
**Pull request by Perseverance42**
This PR implements the proposed changes from #1333, addressing the issue with logging levels. Initially, I intended to use the warn log level, but it appears that the `Warn()` method lacks implementation in "github.com/tendermint/tendermint/libs/log". Therefore, I opted for the error log level to ensure visibility, considering the importance of the logs in question.

To minimize operator confusion, it could be beneficial to further clarify the log messages to indicate that this level of logging is intentional and chosen for its visibility before merging.

# PR Checklist:

- [x] Have you read the [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md)?
- [x] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest master? 
Based on [release/v1.0.x](https://github.com/crypto-org-chain/cronos/tree/release/v1.0.x) since it is the origin of the change in #1328 
- [x] Have you checked your code compiles? (`make`)
- ~~[ ] Have you included tests for any non-trivial functionality?~~
- [x] Have you checked your code passes the unit tests? (`make test`)
- [x] Have you checked your code formatting is correct? (`go fmt`)
- [x] Have you checked your basic code style is fine? (`golangci-lint run`)
- ~~[ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`go list -json -m all | nancy sleuth`)~~
- ~~[ ] If your changes affect the client infrastructure, have you run the integration test?~~
- ~~[ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?~~
~~- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-org-chain/chain-main/blob/master/CHANGELOG.md)?~~
- [x] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md#developer-certificate-of-originn).

I'm eager to learn and improve through this contribution process, so I welcome any feedback or suggestions. 
Thank you for considering my PR.

### CODE REVIEW

**Comment by Perseverance42** [comment]
As per the contribution guidelines, I hereby affirm that my contribution is in accordance with the [Developer's Certificate of Origin](https://developercertificate.org/).

**Comment by Perseverance42** [comment]
I tested the build binary on the production environment and the logging worked as expected.

**Review by yihuang — APPROVED** [review]

**Comment by yihuang** [comment]
@Perseverance42 can you sign the commits?

**Comment by Perseverance42** [comment]
The commit is signed now.

**Review by yihuang — APPROVED** [review]

**Pull request merged**
