### PR TITLE
Problem: potential resource leaks are not checked

### PR DESCRIPTION
**Pull request by tomtau**
Solution: added a CI static analysis for resource leaks

### CODE REVIEW

**Comment by tomtau** [comment]
```
/go/pkg/mod/github.com/evmos/ethermint@v0.6.1-0.20220923160625-35850e620d28/app/ante/eip712.go:236:36: RecoverPubkey not declared by package secp256k1
[13](https://github.com/crypto-org-chain/cronos/actions/runs/3150148588/jobs/5122600259#step:4:13)
/go/pkg/mod/github.com/evmos/ethermint@v0.6.1-0.20220923160625-35850e620d28/app/ante/eip712.go:262:17: VerifySignature not declared by package secp256k1
[14](https://github.com/crypto-org-chain/cronos/actions/runs/3150148588/jobs/5122600259#step:4:14)
resleak: analysis skipped due to errors in package
```

**Comment by tomtau** [comment]
@yihuang for this to work, it'd need to be able to build Ethermint/Cronos without CGO, not sure if that's possible atm?

**Comment by yihuang** [comment]
> @yihuang for this to work, it'd need to be able to build Ethermint/Cronos without CGO, not sure if that's possible atm?

with goleveldb backend it should be possible I think?

**Comment by tomtau** [comment]
yes

**Pull request closed without merging**
