### PR TITLE
Problem: different Gravity Bridge versions used in Nix integration tests and in Go build

### PR DESCRIPTION
**Pull request by yihuang**
Closes: #91

Solution:
- update both to the consolidated cronos branch

👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest master? 
- [ ] Have you checked your code compiles? (`make`)
- [ ] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`make test`)
- [ ] Have you checked your code formatting is correct? (`go fmt`)
- [ ] Have you checked your basic code style is fine? (`golangci-lint run`)
- [ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`go list -json -m all | nancy sleuth`)
- [ ] If your changes affect the client infrastructure, have you run the integration test?
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-org-chain/chain-main/blob/master/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md#developer-certificate-of-originn).

Thank you for your code, it's appreciated! :)

### CODE REVIEW

**Review by tomtau — COMMENTED** [review]
there's a merge conflict + integration tests fail

**Comment by yihuang** [comment]
marked as a draft for now, there's build issue in the Cronos branch of gravity-bridge,

**Review by tomtau — COMMENTED** [review]
looks all right: `test_gravity_transfer` fails with "wait for send-to-cronos" timeout? the only custom breaking change I can think of in gorc is that "keystore" config isn't a string... but gorc isn't used in the integration tests so far?

**Comment by yihuang** [comment]
> looks all right: `test_gravity_transfer` fails with "wait for send-to-cronos" timeout? the only custom breaking change I can think of in gorc is that "keystore" config isn't a string... but gorc isn't used in the integration tests so far?

the issue is the `--hd-wallet-path` flag is not optional, I just changed the integration test.

**Review by thomas-nguy — APPROVED** [review]
lgtm

**Comment by JayT106** [comment]
LGTM

**Pull request merged**
