### PR TITLE
Problem: unable to collect output when mempool is full

### PR DESCRIPTION
**Pull request by mmsqe**
add max_wait_time for detect_idle

👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest master? 
- [ ] Have you checked your code compiles? (`make`)
- [ ] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`make test`)
- [ ] Have you checked your code formatting is correct? (`go fmt`)
- [ ] Have you checked your basic code style is fine? (`golangci-lint run`)
- [ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`go list -json -m all | nancy sleuth`)
- [ ] If your changes affect the client infrastructure, have you run the integration test?
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-org-chain/chain-main/blob/master/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md#developer-certificate-of-originn).

Thank you for your code, it's appreciated! :)

## Summary by CodeRabbit

- **New Features**
	- Introduced a maximum wait time parameter for the idle detection function, improving responsiveness.

- **Bug Fixes**
	- Enhanced control flow to allow for early termination of idle detection based on the new time constraint.

### CODE REVIEW

**Review by yihuang — COMMENTED** [review]
> unable to collect output when mempool is full

Is the chain halted?

**Comment by mmsqe** [comment]
> > unable to collect output when mempool is full
> 
> Is the chain halted?

yes

**Comment by yihuang** [comment]
> > unable to collect output when mempool is full

why full mempool cause chain halt?

**Comment by mmsqe** [comment]
> > > unable to collect output when mempool is full
> 
> why full mempool cause chain halt?

actually not halt but no new block like node is down, might just not enough CPU resource

**Comment by yihuang** [comment]
> > > > unable to collect output when mempool is full
> 
> > 
> 
> > why full mempool cause chain halt?
> 
> 
> 
> actually not halt but no new block like node is down, might just not enough CPU resource

node process is killed?

**Comment by mmsqe** [comment]
> > > > > unable to collect output when mempool is full
> > 
> > 
> > > 
> > 
> > 
> > > why full mempool cause chain halt?
> > 
> > 
> > actually not halt but no new block like node is down, might just not enough CPU resource
> 
> node process is killed?

not itself, but other validators are down ;D

**Review by yihuang — APPROVED** [review]

**Comment by mmsqe** [comment]
there's cpu hotspot in fund step, which can be alleviated after https://github.com/cosmos/cosmos-sdk/pull/21372/files included in 50.x

**Pull request merged**
