### PR TITLE
Problem: memiavl changesets incorrectly unmarshal `KVPairs` with `.Delete = true`

### PR DESCRIPTION
**Pull request by pysel**
Closes: #956 

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest master? 
- [ ] Have you checked your code compiles? (`make`)
- [ ] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`make test`)
- [ ] Have you checked your code formatting is correct? (`go fmt`)
- [ ] Have you checked your basic code style is fine? (`golangci-lint run`)
- [ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`go list -json -m all | nancy sleuth`)
- [ ] If your changes affect the client infrastructure, have you run the integration test?
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-org-chain/chain-main/blob/master/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md#developer-certificate-of-originn).

Thank you for your code, it's appreciated! :)

### CODE REVIEW

**Comment by pysel** [comment]
I will also work on adding more tests for this, just so we do not miss this kind of things anymore

**Review by yihuang — APPROVED** [review]

**Comment by yihuang** [comment]
```golang
diff --git a/memiavl/changeset_test.go b/memiavl/changeset_test.go
index 5e8af4a..7758717 100644
--- a/memiavl/changeset_test.go
+++ b/memiavl/changeset_test.go
@@ -6,13 +6,13 @@ import (
        "github.com/stretchr/testify/require"
 )

-func ChangeSetMarshal(t *testing.T) {
+func TestChangeSetMarshal(t *testing.T) {
        for _, changes := range ChangeSets {
                bz, err := MarshalChangeSet(&changes)
                require.NoError(t, err)

                cs, err := UnmarshalChangeSet(bz)
                require.NoError(t, err)
-               require.Equal(t, changes, cs)
+               require.Equal(t, changes, *cs)
        }
 }
```

The method name is the reason for the test case not run, can you make this change as well, I can't push to this PR.

**Review by yihuang — CHANGES_REQUESTED** [review]
Can you fix the test case name `ChangeSetMarshal` -> `TestChangeSetMarshal`.

**Comment by pysel** [comment]
hey @yihuang! fixed changeset and some errors in `iterator_test.go`. I think ready to merge

**Pull request merged**
